# Generated by Django 4.2 on 2023-05-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField()),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('uncos', 'Новости'), ('articles', 'Статьи')], default='uncos', max_length=10)),
                ('data_pub', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
